/** @format */

import uid from '@/utils/uid';

/**
 * General app event types.
 */
export default class AppEventType {
	static CLOSE = uid('CLOSE');
	static ZOOM = uid('ZOOM');
	static ZOOM_START = uid('ZOOM_START');
	static ZOOM_END = uid('ZOOM_END');
	static PAN = uid('PAN');
	static PAN_START = uid('PAN_START');
	static PAN_END = uid('PAN_END');
	static RESIZE = uid('RESIZE');
	static CHANGE_WIDTH = uid('CHANGE_WIDTH');
	static CHANGE_HEIGHT = uid('CHANGE_HEIGHT');
	static CHANGE_VISIBILITY = uid('CHANGE_VISIBILITY');
	static CHANGE_TIME_RANGE = uid('CHANGE_TIME_RANGE');
	static CHANGE_TIME_RANGE_TWEEN = uid('CHANGE_TIME_RANGE_TWEEN');
	static MOVE = uid('MOVE');
	static ADD_CHILD = uid('ADD_CHILD');
	static REMOVE_CHILD = uid('REMOVE_CHILD');
	static CHANGE_COMPLETE = uid('CHANGE_COMPLETE');
	static CHANGE_COMPLETE_DATA_TERMS = uid('CHANGE_COMPLETE_DATA_TERMS');
	static CHANGE_ACTIVE_EVENT = uid('CHANGE_ACTIVE_EVENT');
	static CHANGE_ACTIVE_VR_SESSION = uid('CHANGE_ACTIVE_VR_SESSION');
	static CHANGE_ACTIVE_VR_EXPERIENCE = uid('CHANGE_ACTIVE_VR_EXPERIENCE');
	static DATA_UPDATED = uid('DATA_UPDATED');
	static CHANGE_ANNOTATIONS = uid('CHANGE_ANNOTATIONS');
	static CHANGE_CONFIG = uid('CHANGE_CONFIG');
	static CHANGE_VIEW = uid('CHANGE_VIEW');
	static CHANGE_DATA_TERMS = uid('CHANGE_DATA_TERMS');
	static CHANGE_TOOLTIP_POINTS = uid('CHANGE_TOOLTIP_POINTS');
	static CHANGE_TOOLTIP_PICK_TYPE = uid('CHANGE_TOOLTIP_PICK_TYPE');
	static CHANGE_X_DOMAIN = uid('CHANGE_X_DOMAIN');
	static CHANGE_X_RANGE = uid('CHANGE_X_RANGE');
	static CHANGE_Y_DOMAIN = uid('CHANGE_Y_DOMAIN');
	static CHANGE_TICK_FORMAT = uid('CHANGE_TICK_FORMAT');
	static CHANGE_OPTIONS = uid('CHANGE_OPTIONS');
	static CHANGE_SILENCE = uid('CHANGE_SILENCE');
	static CHANGE_COLOR_SCALE = uid('CHANGE_COLOR_SCALE');
	static CHANGE_CHART_BACKGROUND = uid('CHANGE_CHART_BACKGROUND');
	static CHANGE_COLOR_SCALE_TYPE = uid('CHANGE_COLOR_SCALE_TYPE');
	static CHANGE_COLOR_SCALE_NAME = uid('CHANGE_COLOR_SCALE_NAME');
	static REDRAW_CHART = uid('REDRAW_CHART');
	static CHANGE_STORE = uid('CHANGE_STORE');
	static CUSTOM_CHART_VIEW_EVENT = uid('CUSTOM_CHART_VIEW_EVENT');
	static CHANGE_VIEW_OPTIONS = uid('CHANGE_VIEW_OPTIONS');
	static LEGEND_SOURCE_UPDATED = uid('LEGEND_SOURCE_UPDATED');
	static UPDATE_LEGEND_VIEW = uid('UPDATE_LEGEND_VIEW');
	static TOGGLE_LEGEND = uid('TOGGLE_LEGEND');
	static CHANGE_SENSORS = uid('CHANGE_SENSORS');
	static UPDATE_CHART_MODULES = uid('UPDATE_CHART_MODULES');
	static CHANGE_CONTEXT = uid('CHANGE_CONTEXT');
	static CHANGE_LINE_STYLE = uid('CHANGE_LINE_STYLE');
	static CHANGE_SKIP_GAPS = uid('CHANGE_SKIP_GAPS');
	static CHANGE_TOOLTIP_POINT_MAP = uid('CHANGE_TOOLTIP_POINT_MAP');
}
